/**
 * Seeded mock id → the UUID that row actually has in Supabase.
 *
 * TEMPORARY BRIDGE, and a twin of `SessionUser.dataId`. Courses still come from
 * `src/data/courses.ts` with short ids (1, 14), but storage paths and RLS
 * key off the real `public.courses.id`. Without this map an upload lands on a
 * path no policy recognises and is refused.
 *
 * Generated by the same UUID v5 derivation the seed generator uses, so it
 * cannot drift. Delete it once courses are read from Supabase.
 */
export const COURSE_UUID: Record<string, string> = {
    "1": "577ea935-461d-53d4-b88b-52ee31473d1b", // Tech Odyssey
    "2": "a011cbb4-addf-58ac-b215-075d496c936f", // Web Development
    "3": "e56df1b0-d187-50bb-911c-a77deba8e2dd", // Python Programming
    "4": "556e576c-a311-5e54-bf14-34d9d37c7184", // Digital Literacy
    "5": "829f6967-e9a3-5172-9892-963a17018cb2", // ArcGIS & Spatial Analysis
    "6": "6c7571e3-9a65-5a1c-abf4-4161116d4da3", // Data Analysis / Data Analytics
    "7": "466129d2-af54-51a4-b4f4-41b16cee9eb9", // DATA PROCESSING
    "8": "d14b913d-d2d5-575b-a6d5-d9f012c0d6cf", // Digital Productivity Tools
    "9": "e4df4b90-8a0a-5e3c-9e30-a7c0d053a927", // Generative AI
    "10": "1297a671-9773-5184-b07d-5038714a7d33", // Routing & Wireless Networking
    "11": "e892e7df-1cfb-5379-9b12-924c9812a944", // Basic Computer Networking
    "13": "505771c5-aa1d-5a7b-9173-395eaee4fc14", // Data Science
    "14": "b4584a3f-bcd0-5a1e-be81-2577f820cbfc", // Cybersecurity
    "15": "1296b991-4846-55c9-bed5-a9d8a3a31ad4", // Digital Marketing
};

/** The id storage and RLS expect for a course, or null when it has no seeded row. */
export function storageCourseId(courseId: string): string | null {
    if (/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(courseId)) return courseId;
    return COURSE_UUID[courseId] ?? null;
}
